# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fBubUW4HeMP6gRnTFZA91H3mgmvDD8Xk

**Red Neuronal Convolucional (CNN) con TensorFlow**

Descripción del problema de clasificación

El objetivo de esta práctica es implementar una Red Neuronal Convolucional (CNN) utilizando TensorFlow y Keras para resolver un problema de clasificación de imágenes.

En este ejemplo se utilizará el dataset MNIST, el cual contiene imágenes de dígitos escritos a mano del 0 al 9.

Cada imagen:

Tiene tamaño de 28x28 píxeles.
Está en escala de grises.
Pertenece a una de 10 clases.

La CNN aprenderá automáticamente características relevantes de las imágenes mediante capas convolucionales y de pooling para posteriormente realizar la clasificación.

**Pipeline**

**Exploración y preprocesamiento del Dataset**
Importar librerías
"""

import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
import numpy as np

"""**Cargar el dataset MNIST**"""

# Cargar dataset
(train_images, train_labels), (test_images, test_labels) = datasets.mnist.load_data()

print("Training images shape:", train_images.shape)
print("Testing images shape:", test_images.shape)

"""**Visualización de imágenes**"""

# Mostrar algunas imágenes
plt.figure(figsize=(10,10))

for i in range(9):
    plt.subplot(3,3,i+1)
    plt.imshow(train_images[i], cmap='gray')
    plt.title("Label: {}".format(train_labels[i]))
    plt.axis('off')

plt.show()

"""**Normalización de imágenes**

La normalización ayuda a mejorar el entrenamiento de la red neuronal.
"""

# Normalizar valores entre 0 y 1
train_images = train_images / 255.0
test_images = test_images / 255.0

"""**Redimensionar imágenes para CNN**

Las CNN requieren un canal adicional.
"""

# Agregar dimensión del canal
train_images = train_images.reshape((60000, 28, 28, 1))
test_images = test_images.reshape((10000, 28, 28, 1))

print(train_images.shape)

"""**CNN Architecture**
Construcción de la CNN
"""

# Crear modelo secuencial
model = models.Sequential()

# Primera capa convolucional
model.add(layers.Conv2D(32, (3,3), activation='relu',
                        input_shape=(28,28,1)))

# Pooling
model.add(layers.MaxPooling2D((2,2)))

# Segunda capa convolucional
model.add(layers.Conv2D(64, (3,3), activation='relu'))

# Segundo pooling
model.add(layers.MaxPooling2D((2,2)))

# Tercera capa convolucional
model.add(layers.Conv2D(64, (3,3), activation='relu'))

# Aplanar datos
model.add(layers.Flatten())

# Capa densa
model.add(layers.Dense(64, activation='relu'))

# Capa de salida
model.add(layers.Dense(10, activation='softmax'))

"""Resumen del modelo"""

model.summary()

"""Explicación de la arquitectura

La arquitectura implementada contiene:

Capas convolucionales:
Extraen características importantes.
Capas MaxPooling:
Reducen dimensionalidad.
Flatten:
Convierte matrices a vectores.
Dense:
Realiza la clasificación final.
Softmax:
Genera probabilidades para las 10 clases.

**Model Training**
Compilar el modelo
"""

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

"""Entrenamiento del modelo"""

history = model.fit(train_images,
                    train_labels,
                    epochs=5,
                    validation_data=(test_images, test_labels))

"""**Visualización del accuracy**"""

plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')

plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

"""Model Prediction
Realizar predicciones
"""

predictions = model.predict(test_images)

"""**Predicción de una imagen**"""

# Mostrar imagen
plt.imshow(test_images[0].reshape(28,28), cmap='gray')
plt.show()

# Clase predicha
predicted_class = np.argmax(predictions[0])

print("Predicción:", predicted_class)
print("Etiqueta real:", test_labels[0])

"""
Evaluar el modelo"""

test_loss, test_acc = model.evaluate(test_images,
                                     test_labels,
                                     verbose=2)

print("Test Accuracy:", test_acc)
print("Test Loss:", test_loss)

"""Matriz de confusión"""

from sklearn.metrics import confusion_matrix
import seaborn as sns

# Obtener predicciones finales
y_pred = np.argmax(predictions, axis=1)

# Matriz de confusión
cm = confusion_matrix(test_labels, y_pred)

# Visualización
plt.figure(figsize=(10,8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')

plt.xlabel('Predicted')
plt.ylabel('Real')
plt.title('Confusion Matrix')

plt.show()

"""Model Storing (Almacenamiento del modelo)
Guardar modelo entrenado
"""

model.save("cnn_mnist_model.h5")

print("Modelo guardado correctamente")

"""Cargar modelo almacenado"""

from tensorflow.keras.models import load_model

new_model = load_model("cnn_mnist_model.h5")

print("Modelo cargado correctamente")

"""Conclusión

En esta práctica se implementó una Red Neuronal Convolucional utilizando TensorFlow/Keras para resolver un problema de clasificación de imágenes.

La CNN logró aprender características importantes del dataset MNIST mediante capas convolucionales y pooling, obteniendo una alta precisión en la clasificación de dígitos escritos a mano.

Además, se desarrolló todo el pipeline de Machine Learning:

Exploración de datos.
Preprocesamiento.
Diseño de arquitectura CNN.
Entrenamiento.
Predicción.
Evaluación.
Almacenamiento del modelo.

Este tipo de arquitecturas son ampliamente utilizadas en:

Visión computacional.
Reconocimiento facial.
Vehículos autónomos.
Diagnóstico médico.
Sistemas inteligentes.
"""